<a href="https://colab.research.google.com/github/daapri/_Talento_tech_2024/blob/main/Proyecto_final_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<H1> INTRODUCCIÓN

En el mundo actual, el entretenimiento audiovisual ha cobrado un papel fundamental en la vida de las personas. Netflix, como uno de los principales proveedores de servicios de streaming, ofrece una amplia variedad de películas que satisfacen diversos gustos y preferencias.

Este análisis se centra en un conjunto de datos de películas disponibles en Netflix, recopilado mediante extracción de datos web del sitio web de IMDB y publicado en Kaggle. El objetivo principal es explorar y analizar estos datos para comprender mejor las características de las películas que se ofrecen en la plataforma, así como identificar patrones y tendencias que puedan ser relevantes.

A partir de este análisis, se espera obtener resultados que contribuyan al reconocimiento del aprendizaje académico

---

In [1]:
#importo librerias a usar para limpieza de datos
import pandas as pd #Manipulación de datos
import matplotlib.pyplot as plt #Graficó de datos
import numpy as np #Trabaja con datos numéricos
import seaborn as sns #Grafícos mas especializados

In [2]:
# importar base de datos
ruta = "/content/n_movies.csv"
data = pd.read_csv(ruta, encoding='latin-1') # utiliza Pandas para leer el archivo CSV y convertirlo en tabla

In [3]:
print(data.shape)#mostrar las dimensiones de mis datos

(9957, 9)

In [ ]:
# la dataframe cuenta con 9957 filas y 9 columnas

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9957 entries, 0 to 9956
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        9957 non-null   object
 1   year         9430 non-null   object
 2   certificate  6504 non-null   object
 3   duration     7921 non-null   object
 4   genre        9884 non-null   object
 5   rating       8784 non-null   float64
 6   description  9957 non-null   object
 7   stars        9957 non-null   object
 8   votes        8784 non-null   object
dtypes: float64(1), object(8)
memory usage: 700.2+ KB

In [5]:
data.head(10)

,title,year,certificate,duration,genre,rating,description,stars,votes
0,Cobra Kai,(2018â ),TV-14,30 min,"Action, Comedy, Drama",8.5,Decades after their 1984 All Valley Karate Tou...,"['Ralph Macchio, ', 'William Zabka, ', 'Courtn...","177,031"
1,The Crown,(2016â ),TV-MA,58 min,"Biography, Drama, History",8.7,Follows the political rivalries and romance of...,"['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...","199,885"
2,Better Call Saul,(2015â2022),TV-MA,46 min,"Crime, Drama",8.9,The trials and tribulations of criminal lawyer...,"['Bob Odenkirk, ', 'Rhea Seehorn, ', 'Jonathan...","501,384"
3,Devil in Ohio,(2022),TV-MA,356 min,"Drama, Horror, Mystery",5.9,When a psychiatrist shelters a mysterious cult...,"['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...","9,773"
4,Cyberpunk: Edgerunners,(2022â ),TV-MA,24 min,"Animation, Action, Adventure",8.6,A Street Kid trying to survive in a technology...,"['Zach Aguilar, ', 'Kenichiro Ohashi, ', 'Emi ...","15,413"
5,The Sandman,(2022â ),TV-MA,45 min,"Drama, Fantasy, Horror",7.8,Upon escaping after decades of imprisonment by...,"['Tom Sturridge, ', 'Boyd Holbrook, ', 'Patton...","116,358"
6,Rick and Morty,(2013â ),TV-MA,23 min,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"['Justin Roiland, ', 'Chris Parnell, ', 'Spenc...","502,160"
7,Breaking Bad,(2008â2013),TV-MA,49 min,"Crime, Drama, Thriller",9.5,A high school chemistry teacher diagnosed with...,"['Bryan Cranston, ', 'Aaron Paul, ', 'Anna Gun...","1,831,340"
8,The Imperfects,(2022â ),TV-MA,45 min,"Action, Adventure, Drama",6.3,After an experimental gene therapy turns them ...,"['Morgan Taylor Campbell, ', 'Italia Ricci, ',...","3,123"
9,Blonde,(2022),NC-17,166 min,"Biography, Drama, Mystery",6.2,A fictionalized chronicle of the inner life of...,"['Andrew Dominik', '| ', ' Stars:', 'Ana de...",935

se puede observar que nuestra DataFrame tiene 9 columnas de las cuales 1 tiene valores flotantes y 8 valores categoricos

In [6]:
# Para realizar la limpieza de nuestra dataframe seguiremos pasos como: 1. Revisar si hay datos faltantes en alguna celda. 2. Depurar columnas irrelevantes, 3. Observar los registros repetidos, 4. Revisar los outlies (valores externos), 5. Corregir errores tipográficos

data.dropna(inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5754 entries, 0 to 9956
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        5754 non-null   object
 1   year         5754 non-null   object
 2   certificate  5754 non-null   object
 3   duration     5754 non-null   object
 4   genre        5754 non-null   object
 5   rating       5754 non-null   float64
 6   description  5754 non-null   object
 7   stars        5754 non-null   object
 8   votes        5754 non-null   object
dtypes: float64(1), object(8)
memory usage: 449.5+ KB

Se elimanron aquellas filas con valores faltantes usando

In [9]:
cols_cat=["title","year","certificate","duration","genre","rating","description","stars","votes"]
for col in cols_cat:
  print(f"columna{col}:{data[col].nunique()} subniveles")

columnatitle:4413 subniveles
columnayear:405 subniveles
columnacertificate:19 subniveles
columnaduration:285 subniveles
columnagenre:455 subniveles
columnarating:78 subniveles
columnadescription:5700 subniveles
columnastars:5186 subniveles
columnavotes:4236 subniveles